# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pomme < Formula
  desc "A powerful CLI tool for App Store Connect analytics, sales reports, and app management"
  homepage "https://github.com/marcusziade/pomme"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/Pomme/releases/download/2.0.0/Pomme_Darwin_x86_64.tar.gz"
      sha256 "adcd07a40bfd058e03456e4b89579b397bfe753f71a4aa5e589072e43bf45f65"

      def install
        bin.install "pomme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/Pomme/releases/download/2.0.0/Pomme_Darwin_arm64.tar.gz"
      sha256 "071c9c3f4f758a98509479f9450dc563951fa2f6aa1b3d6fd40e4b935b797a5a"

      def install
        bin.install "pomme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/Pomme/releases/download/2.0.0/Pomme_Linux_x86_64.tar.gz"
      sha256 "b491a277598af54133703d6e53eec6d034c1c22a62c474b02efed0e5f816bcd9"
      def install
        bin.install "pomme"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/Pomme/releases/download/2.0.0/Pomme_Linux_arm64.tar.gz"
      sha256 "1c294eacece75100c86acd5de79af54181059103286cad63e96ae922b5268674"
      def install
        bin.install "pomme"
      end
    end
  end

  test do
    system "#{bin}/pomme", "--version"
  end
end
