# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pomme < Formula
  desc "A powerful CLI tool for App Store Connect analytics, sales reports, and app management"
  homepage "https://github.com/marcusziade/pomme"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/Pomme/releases/download/2.0.0/Pomme_Darwin_x86_64.tar.gz"
      sha256 "4c686d434bf5e5beb1eb758128b362427cc7808c1439aba0204a7714e2345056"

      def install
        bin.install "pomme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/Pomme/releases/download/2.0.0/Pomme_Darwin_arm64.tar.gz"
      sha256 "ff3dabe14ed4ba907214b89dccf3822484f5221e508433cf01860492a55a97e0"

      def install
        bin.install "pomme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/Pomme/releases/download/2.0.0/Pomme_Linux_x86_64.tar.gz"
      sha256 "c0a3512b17a12e8b44303be2c9940961a3afbef5e6475b5bdab0b4fb09cc0c3c"
      def install
        bin.install "pomme"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/Pomme/releases/download/2.0.0/Pomme_Linux_arm64.tar.gz"
      sha256 "4b2f265ba7a8fae57924e6894fb334756d16b5e36d3b69f3be0a79ce75cbc7b7"
      def install
        bin.install "pomme"
      end
    end
  end

  test do
    system "#{bin}/pomme", "--version"
  end
end
