# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pomme < Formula
  desc "A powerful CLI tool for App Store Connect analytics, sales reports, and app management"
  homepage "https://github.com/marcusziade/pomme"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/pomme/releases/download/2.0.0/pomme_Darwin_x86_64.tar.gz"
      sha256 ""

      def install
        bin.install "pomme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/pomme/releases/download/2.0.0/pomme_Darwin_arm64.tar.gz"
      sha256 ""

      def install
        bin.install "pomme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/pomme/releases/download/2.0.0/pomme_Linux_x86_64.tar.gz"
      sha256 ""

      def install
        bin.install "pomme"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/pomme/releases/download/2.0.0/pomme_Linux_arm64.tar.gz"
      sha256 ""

      def install
        bin.install "pomme"
      end
    end
  end

  test do
    system "#{bin}/pomme", "--version"
  end
end