# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeedrunCli < Formula
  desc "Browse speedrun.com leaderboards from your terminal"
  homepage "https://github.com/marcusziade/speedrun-cli"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/speedrun-cli/releases/download/1.4.1/speedrun-cli_Darwin_x86_64.tar.gz"
      sha256 "a1d97a462e186b71ade6873ac29c49613d8c61a2266e233777bc173efee42d25"

      def install
        bin.install "speedrun-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/speedrun-cli/releases/download/1.4.1/speedrun-cli_Darwin_arm64.tar.gz"
      sha256 "24eb21ea427cbfd2df7f3b9b15a09d5630f20d96f0c663a9cd63fea4b3818083"

      def install
        bin.install "speedrun-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/speedrun-cli/releases/download/1.4.1/speedrun-cli_Linux_x86_64.tar.gz"
      sha256 "6008f946b2c88a9a135887e9f097e7e0450bea1bd87780e741cf0b36d1998b44"
      def install
        bin.install "speedrun-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/speedrun-cli/releases/download/1.4.1/speedrun-cli_Linux_arm64.tar.gz"
      sha256 "5ce873ad577ab9aa01308a152f08944d1c32ed81afb86f3c534fca57176cd63a"
      def install
        bin.install "speedrun-cli"
      end
    end
  end

  test do
    system "#{bin}/speedrun-cli", "--version"
  end
end
