# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeedrunCli < Formula
  desc "Browse speedrun.com leaderboards from your terminal"
  homepage "https://github.com/marcusziade/speedrun-cli"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/speedrun-cli/releases/download/1.4.0/speedrun-cli_Darwin_x86_64.tar.gz"
      sha256 "695947094021f6d32625df00504ac1c521c421a851e7d8e27b90ac15d9872daa"

      def install
        bin.install "speedrun-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/speedrun-cli/releases/download/1.4.0/speedrun-cli_Darwin_arm64.tar.gz"
      sha256 "23a2bce9441c59c4142923eb932091331860a25c3b92981144e2bd3b4d3701d1"

      def install
        bin.install "speedrun-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/speedrun-cli/releases/download/1.4.0/speedrun-cli_Linux_x86_64.tar.gz"
      sha256 "739db6e6a892112e7f966a55e4f6fe5dc43860f511bee0f1d266072e4cb8116b"
      def install
        bin.install "speedrun-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/speedrun-cli/releases/download/1.4.0/speedrun-cli_Linux_arm64.tar.gz"
      sha256 "daadff8dfa01c3a5258158bce48d09fbd19be3187d6e5d4913349fea3c0c5a35"
      def install
        bin.install "speedrun-cli"
      end
    end
  end

  test do
    system "#{bin}/speedrun-cli", "--version"
  end
end
